apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthcare-staging

resources:
- ../../base

patches:
- target:
    kind: ConfigMap
    name: healthcare-config
  patch: |-
    - op: replace
      path: /data/environment
      value: "Staging"
    - op: replace
      path: /data/logging__LogLevel__Default
      value: "Information"
    - op: replace
      path: /data/CORS__AllowedOrigins
      value: "https://staging.healthcare.example.com"

- target:
    kind: Deployment
    name: healthcare-app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "200m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "500m"

- target:
    kind: HorizontalPodAutoscaler
    name: healthcare-app-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 2
    - op: replace
      path: /spec/maxReplicas
      value: 5

- target:
    kind: Ingress
    name: healthcare-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "staging.healthcare.example.com"
    - op: replace
      path: /spec/tls/0/hosts/0
      value: "staging.healthcare.example.com" 